{"start": 1523252371383, "fullName": "test_demo1.TestBar#test_bar2", "name": "测试报告2", "stop": 1523252371386, "steps": [{"start": 1523252371383, "status": "passed", "stop": 1523252371383, "name": "步骤一"}, {"start": 1523252371383, "status": "passed", "stop": 1523252371383, "name": "步骤二"}, {"start": 1523252371383, "name": "步骤三", "stop": 1523252371386, "attachments": [{"source": "bda69679-c278-4858-b69c-5bcf07651fa1-attachment.attach", "name": "具体内容"}], "status": "failed", "statusDetails": {"trace": "  File \"E:\\Nahsor\\test_demo1.py\", line 32, in test_bar2\n    assert False\n", "message": "AssertionError: assert False\n"}}], "labels": [{"value": "testsuite2", "name": "feature"}, {"value": "testcass2", "name": "story"}, {"value": "testcass3", "name": "story"}, {"value": "testcass4", "name": "story"}, {"value": "DESKTOP-5PN9VPJ", "name": "host"}, {"value": "3600-Thread-1", "name": "thread"}, {"value": "pytest", "name": "framework"}, {"value": "cpython3", "name": "language"}, {"value": "test_demo1", "name": "package"}], "status": "failed", "historyId": "ae3b472d7595459a20e0469e7ce9ae96", "statusDetails": {"trace": "self = <test_demo1.TestBar object at 0x000001A339434F28>\n\n    @allure.title(\"测试报告2\")\n    def test_bar2(self):\n        with allure.step(\"步骤一\"):\n            assert True\n        with allure.step(\"步骤二\"):\n            assert True\n        with allure.step(\"步骤三\"):\n            allure.attach('失败的步骤', '具体内容')\n>           assert False\nE           assert False\n\ntest_demo1.py:32: AssertionError", "message": "AssertionError: assert False"}, "uuid": "67160109-d3a0-4eef-8abc-941bf0161ced"}