{"name": "name2", "status": "failed", "statusDetails": {"message": "conftest.JsonException: (<JsonItem 'name2'>, 'test2', 'test3')", "trace": "usecase execution failed\n   spec failed: 'test2': 'test3'\n   no further details known at this point."}, "start": 1524164641805, "stop": 1524164641806, "uuid": "f4c81550-71a5-44be-8e82-fbb7fe227b0c", "historyId": "28b699d8f6bf4edd23204f35d640b915", "fullName": "test_json#name2", "labels": [{"name": "host", "value": "LangJin"}, {"name": "thread", "value": "4160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_json"}]}